### ISSUE TITLE
Custom controls via settings not (easily) possible

### ISSUE THREAD

**Issue by kdambekalns** [jonnitto/Jonnitto.Plyr#26]
**Describe the bug**

Plyr controls cannot be changed as expected.

**To Reproduce**

```
Jonnitto:
  Plyr:
    options:
      # hacky solution to override the defaults - "shortening" lists in YAML is not possible
      controls: ['play']
```

**Expected behavior**

Only the `play` control is used.

** Actual behavior**

As can be seen with `./flow configuration:show --type Settings --path Jonnitto.Plyr.options.controls` the `play` is added to the defaults. Thus all default controls are shown.

**Workaround**

```
Jonnitto:
  Plyr:
    options:
      # hacky solution to override the defaults - "shortening" lists in YAML is not possible
      controls: [null, 'play', null, null, null, null, null, null, null, null, null]
```

The trick is to use as many `null` entries as there are default entries in the list. See https://discuss.neos.io/t/how-to-replace-an-array-in-settings-yaml/296 for more on this (from 2015!)
